[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
merkle_action_solana = "6xG5d22pnarYAgNySzEmEwkQ9jLGP8bexwFWDDMjvU25"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dreamdevfast/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
